export const SAVE_TO_STORE = 'SAVE_TO_STORE';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const SHOW_MORE_DATA = 'SHOW_MORE_DATA';
export const UPDATE_FETCHING_STATUS = 'UPDATE_FETCHING_STATUS';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';